### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by TechnologyClassroom** [cockroachlabs/open-sourced-interview-process#6]
This project has [no license](https://choosealicense.com/no-license/).  I would suggest using a license for [non-software](https://choosealicense.com/non-software/).

Specifically, I would suggest licensing this project using the [CC BY-SA 4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) license.  I have [an example](https://github.com/TechnologyClassroom/RaspberryPiProgrammingWorkshop/blob/master/LICENSE.md) of using CC BY-SA on github.

**Comment by bdarnell** [comment]
Thanks for the reminder; we definitely want to use a creative commons license here. We use CC BY 4.0 in [our docs repo](https://github.com/cockroachdb/docs/blob/master/LICENSE), so I'd probably do the same here (or maybe even CC0?) instead of the ShareAlike version

**Comment by bdarnell** [comment]
OK, it's official: I've added a CC0 license in 2ade60d20ea77ce6ec7658672e38318c0a132e83
